size: 2Gi
configMapName: airflow-config
customPGImage: "postgres:14.4-alpine"
replicas: 2
wal_level: logical
logging_collector: true
log_statement: 'none'
db_name: airflow
db_user: user_airflow
db_password: airflow
