apiVersion: v1
kind: Service
metadata:
  labels:
    app: @service-name
    replicationRole: primary
  name: @service-name-nodeport
  namespace: @service-ns
  ownerReferences:
  - apiVersion: kubegres.reactive-tech.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kubegres
    name: @service-name
    uid: @service-uid
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: @service-port
  selector:
    app: @service-name
    replicationRole: primary
  sessionAffinity: None
