apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  awsAccessKey: {{ .Values.kafkaConnectAwsAccessKey }}
  awsSecretAccessKey: {{ .Values.kafkaConnectAwsSecretAccessKey }}