apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bkp-pvc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
