---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-sink-s3-connector
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    #key.converter: io.confluent.connect.avro.AvroConverter
    #value.converter: io.confluent.connect.avro.AvroConverter
    #key.converter.schemas.enable: false
    #value.converter: org.apache.kafka.connect.avro.AvroConverter
    #value.converter.schemas.enable: true
    connector.class: io.confluent.connect.s3.S3SinkConnector
    topics: jhodb-debezium.ecommerce.tabela
    s3.region: us-east-1
    s3.bucket.name: jho-confluent-kafka-connect-s3-testing
    s3.part.size: 5242880
    flush.size: 100
    rotate.schedule.interval.ms: 60000
    storage.class: io.confluent.connect.s3.storage.S3Storage
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    #format.class: io.confluent.connect.s3.format.parquet.ParquetFormat
    schema.generator.class: io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    schema.compatibility: NONE
    timezone: "UTC"
